### ISSUE TITLE
confused about only replace unet mode for inpainting

### ISSUE THREAD

**Issue by renrenzsbbb** [haofanwang/ControlNet-for-Diffusers#9]
Thanks for your great work. the inpaiting function is amazing. but I am confused why the inpaint works by only replacing unet weight.

**Comment by haofanwang** [comment]
The idea behind is quite simple. @renrenzsbbb 

- The ControlNet is of two modules, one is frozen stable-diffusion-1.5 base-model, the other is a new sub-model for controlling.

- The Stable-Diffusion-Inpainting model is also stable-diffusion-1.5 based, only the UNet part is trained (with extra input channel) to support image+mask input.

Thus, to equip ControlNet with inpainting ability, we can directly replace the UNet. But please note that this is only because they already share same model structure and frozen layers, if not, the performance will degrade significantly.

**Comment by renrenzsbbb** [comment]
Thanks
